### ISSUE TITLE
monolingual make rules and sample corpus for apertium-tagger .prob training

### ISSUE THREAD

**Issue by unhammer** [goavki/bootstrap#25]
We should have some make rules for the unigram tagger, along with a tiny sample corpus of the right format (e.g. in the subdir corpus). Something like
```
LANG.prob: corpus/LANG.corpus
	apertium -d . tagger-training-pipeline <$< >$@
```
(Someone with an idea what the tagger training pipeline looks like will have to fill that out.)

**Comment by ftyers** [comment]
```
$(LANG1).prob: corpus/$(LANG1).tagged
        apertium-tagger -s 0 -u 2 $@ $<
```

**Comment by ftyers** [comment]
Ok, this is implemented in `apertium-kaz`
